本日の天気コンポーネントの実装
kenta-0615/react-weather-app pull request #18
Opened 2022-05-25 05:38 UTC by kenta-0615

close #1
@taishi1116 
# 本日の天気コンポーネントの実装
* APIの実装は無しの外観だけの実装です。
* ストーリーブックでデザインは確認済み

2022-05-25 07:29 UTC, taishi1116 requested changes
@kenta-0615 
コメントしました！

2022-05-25 07:29 UTC, taishi1116 commented on src/components/TodayWeather.tsx
> +	todayTemperature: number;
todayWeatherという名前のコンポーネントなのでtemperatureだけで伝わりそう

2022-05-25 07:29 UTC, taishi1116 commented on src/components/TodayWeather.tsx
> +	todayWeather: string;
todayWeatherという名前のコンポーネントでprops名がtodayWeatherなので何を渡したらよいかわからなかった。ここって何が入る?

2022-05-25 07:46 UTC, kenta-0615 commented on src/components/TodayWeather.tsx
> +	todayWeather: string;
@taishi1116 
# todayWeather
* APIから取得した今日の天気が入るところです。

2022-05-25 07:52 UTC, kenta-0615 reviewed
close #1 
@taishi1116 
# 本日の天気コンポーネントの修正です
■修正箇所
* todayTemperatur → tmperaturに変更

2022-05-25 08:09 UTC, taishi1116 commented on src/components/TodayWeather.tsx
> +	todayWeather: string;
天気名が入るんだよね！ならweatherNameとかweatherTelopとかの方がわかりやすいのでは?
叩くAPIもtelopというプロパティで天気名を返しているっぽい
https://weather.tsukumijima.net/

2022-05-25 08:09 UTC, taishi1116 commented
closeとかってPRの説明文に書いとくだけで紐づくのでコメントで入らないよー！

2022-05-27 05:00 UTC, taishi1116 requested changes
@kenta-0615 
追加コメントしました！

2022-05-27 05:00 UTC, taishi1116 commented on src/components/TodayWeather.tsx
> +	telopWeather: string;
なんとなくで英語をつけるのではなく、意味を考えてみてください！
今回はお天気のテロップをpropsとして渡す認識です！
`telopWearher`だと`テロップ天気`という意味になってテロップが天気を修飾しています！
やるならweatherTelopですが、これもコンポーネント名からわかるのでtelopでいい気がしています

2022-05-27 09:43 UTC, taishi1116 commented on src/components/TodayWeather.tsx
> +	telopWeather: string;
[6e44d86](https://github.com/kenta-0615/react-weather-app/pull/18/commits/6e44d865786fdf8ef55ee7cd07e3cac69fecb2fc) で修正

2022-05-27 09:44 UTC, taishi1116 commented
@kenta-0615 

pushするだけでなくて、指摘コメントに対してどのコミットで直したかをコメントいただけると
https://github.com/kenta-0615/react-weather-app/pull/18#discussion_r883452593

2022-05-27 09:47 UTC, taishi1116 commented
LGTM

<img width="1792" alt="スクリーンショット 2022-05-27 18 47 05" src="https://user-images.githubusercontent.com/58138538/170675431-7c057610-6555-4d8f-a28e-f18fdb14aaab.png">

2022-05-27 09:47 UTC, taishi1116 approved these changes

2022-05-27 11:29 UTC, merged