Buttonコンポーネントのデザインの実装
kenta-0615/react-weather-app pull request #20
Opened 2022-05-28 07:01 UTC by kenta-0615

close #19 
## 内容
- [] buttonコンポーネントの実装
- [] storybookで確認できる
## 確認手順
- [] issue-#19-add-button-component branchをpullする
- [] npm run storybookを実行する

2022-05-29 00:52 UTC, taishi1116 requested changes
@kenta-0615 
何点かコメントしました〜！

2022-05-29 00:52 UTC, taishi1116 commented on src/components/ButtonList.tsx
> +export const Button: React.FC<Props> = ({ title }) => {
ボタンを1つしか表現しないのにファイル名がButtonListとなっていることに違和感があります！
基本的にファイル名とコンポーネント名は同じになるかと！

2022-05-29 00:52 UTC, taishi1116 commented on src/stories/ButtonList.stories.tsx
> +	<div>
このdivタグってスタイルとか当たっていないので不要かと！

2022-05-29 00:52 UTC, taishi1116 commented on src/stories/ButtonList.stories.tsx
> +	title: "Button Component",
今までは末尾にコンポーネントとかついていなかったはずです！
この辺りの規則性も意識してください！
<img width="1296" alt="スクリーンショット 2022-05-29 9 51 05" src="https://user-images.githubusercontent.com/58138538/170847468-b70799d3-0b5f-40e6-8ef3-cefc31dc280c.png">

2022-05-29 00:52 UTC, taishi1116 commented on src/components/ButtonList.tsx
> +		<div className="relative flex justify-between mb-10">
ここのスタイルってボタンの何を設定していますか?ぱっと見だとわからなかったので教えていただけると！

2022-05-29 05:37 UTC, kenta-0615 commented on src/components/ButtonList.tsx
> +		<div className="relative flex justify-between mb-10">
@taishi1116 
このスタイルはbutton外のマージンとか配列の要素をこのスタイルで決めてます。

2022-05-29 05:53 UTC, taishi1116 commented on src/components/ButtonList.tsx
> +		<div className="relative flex justify-between mb-10">
> ボタン外

ボタン自体の大きさではないってことだよね？

2022-05-30 00:32 UTC, taishi1116 requested changes
@kenta-0615 

1点追加コメントしています

2022-05-30 00:32 UTC, taishi1116 commented on src/components/Button.tsx
> +		<div className="relative flex justify-between mb-10">
storybook開いてみたけど、ここのここの9行目のスタイルっていらない気がしています！
コンポーネントはあくまで部品であり、外のスタイルのことは知らないはずなので！



<img width="507" alt="スクリーンショット 2022-05-30 9 30 01" src="https://user-images.githubusercontent.com/58138538/170897957-73c591ba-793a-45b8-841b-e2656a93e717.png">

2022-05-30 07:16 UTC, kenta-0615 reviewed
@taishi1116 
## 内容
- ButtonConponent内のスタイルの削除

2022-05-30 08:02 UTC, taishi1116 approved these changes
LGTM！！

2022-05-30 16:14 UTC, merged