InputComponentの実装
kenta-0615/react-weather-app pull request #21
Opened 2022-06-01 06:45 UTC by kenta-0615

close #3 
## 内容
- [ ] inputフォームのコンポーネントを実装
- [ ] storybookで確認済み 

## 確認手順
- [ ] 自分のローカル上にgit pullをする
- [ ] npm run storybookを実行

2022-06-01 06:54 UTC, taishi1116 requested changes
@kenta-0615 
何点かコメントしました

2022-06-01 06:54 UTC, taishi1116 commented on src/components/InputForm.tsx
> +export const InputForm: React.FC = () => {
# 命名
inputタグはフォームを構成する入力欄という1つの要素の認識なのでinputFormという命名は異なる気がします
inputコンポーネントやbuttonコンポーネントで構成されたコンポーネントがFormになるかと

2022-06-01 06:54 UTC, taishi1116 commented on src/components/InputForm.tsx
> +			<span className="absolute inset-y-0 left-0 flex items-center pl-2">
inputコンポーネントのはずなのにとてもコードが複雑に見えます。。。
svgタグで実装している部分って多分画像だよね?これって画像をダウンロードしてそのまま使うとかじゃダメ?

2022-06-02 04:19 UTC, kenta-0615 commented on src/components/InputForm.tsx
> +export const InputForm: React.FC = () => {
@taishi1116 
改善します！

2022-06-02 06:26 UTC, kenta-0615 reviewed
@taishi1116 
## 内容
- Input ComponentのInputForm→input変更
- inputの画像を直接ソースに挿入させる
## 状況
- input名の変更は完了。
- input内の画像を実装したが表示が上手くいかない。
- 差分が表示されないので再度"git add"を実行するのでそちらの確認お願い致します。

2022-06-02 06:59 UTC, taishi1116 commented
>  input内の画像を実装したが表示が上手くいかない。

ただ動かないだけだとこちらも見当がつかないので、健太が画像を表示させるためにやったことなど記載いただけると

https://qiita.com/seki_uk/items/4001423b3cd3db0dada7

2022-06-02 11:28 UTC, kenta-0615 commented
@taishi1116 
## 画像出力のためにやったこと
- imagesディレクトリを作成し、画像を取得できるようにした。
- Input.tsxにimgタグで取得できるようにした。
- しかし、出力されなかったのでsvgの出力方法で試すも表示されず
　参考資料：https://larainfo.com/blogs/tailwind-css-input-form-examples
- storybookの実装がそもそもダメなのかと考察し、storybookの変更したものの表示されず
　https://storybook.js.org/docs/react/configure/images-and-assets

2022-06-02 16:19 UTC, kenta-0615 reviewed
@taishi1116 
## 内容
- [ ] inputの虫眼鏡の画像を表示
- [ ] imagesディレクトリをsrcディレクトリ内に作成
- [ ] InputComponentにimportし、画像を表示成功

2022-06-03 01:10 UTC, taishi1116 approved these changes
storybookで確認できました！LGTM

<img width="1792" alt="スクリーンショット 2022-06-03 10 10 26" src="https://user-images.githubusercontent.com/58138538/171767810-877cf68e-cdb5-4f15-bb09-6aed2d0098f8.png">

2022-06-03 01:15 UTC, merged