地域コンポーネントの実装
kenta-0615/react-weather-app pull request #24
Opened 2022-06-04 06:13 UTC by kenta-0615

@taishi1116 
## 内容
- [ ] 地域の表示が出るカードのコンポーネントの実装
- [ ] 矢印の実装は、svgをインポートして実装
## 確認手順
- [ ] 手元にpullをしてnpm run storybookを実行
- [ ] 地域の名前の出るボタン形式の実装が出てくること

2022-06-04 12:56 UTC, taishi1116 requested changes
@kenta-0615 
コメントしました！

2022-06-04 12:56 UTC, taishi1116 commented on src/components/AreaCard.tsx
> +			東京
ここの名前が固定になっているのはなんででしょうか?

2022-06-04 13:04 UTC, taishi1116 commented on src/components/AreaCard.tsx
> +			className="text-white bg-gray-700 w-96 h-16 px-5 py-2.5 inline-center text-center inline-flex items-center"
onCLickハンドラーがないのでクリックされた時の挙動を追加できなさそうだけど大丈夫？

2022-06-04 14:30 UTC, kenta-0615 reviewed
@taishi1116 
## 内容
- [ ] 名前を固定ではなく、propsで渡すように変更
- [ ] onClickのイベントを追加し、コンソールログでクリックされたことを確認できるようにした。
- [ ] ホーバー機能も追加

2022-06-04 14:55 UTC, taishi1116 commented on src/components/AreaCard.tsx
> +			onClick={() => console.log("クリックされたよ")}
地域によってonClick時の挙動は異なると思うのでここもpropsでないといけないと思います

- ロンドンを押したらロンドンの天気を検索する
- 東京を押したら東京の検索をする


このようにonClickは挙動が変わってくる

2022-06-05 06:25 UTC, kenta-0615 reviewed
@taishi1116 
## 内容
- [ ] AreaCardComponentに直接onClickを入れていたものをpropsで渡せるように変更

2022-06-05 07:37 UTC, taishi1116 approved these changes

2022-06-05 07:40 UTC, merged