WIP: APIの実装
kenta-0615/react-weather-app pull request #28
Opened 2022-06-10 13:44 UTC by kenta-0615

close #10 
## 内容
- axiosのTypescriptとReactの書き方で実装
  - https://syachiku.net/reacttypescript-axios/
- npm install axiosでインストール完了
- その後、テストでApp.tsxに既述
- npm startを実行
## 現在の状況
- 画面上にデータの表示がされない
- APIの方で404 (Not Found)エラーを検知
## 試したこと
- APIの状況を確認したところ404NOT FOUNDが表示 
  - https://weather.tsukumijima.net/api/forecast/city
- APIの状況が確認できない
- サイトの福岡管区気象台の情報は確認できる
  - https://weather.tsukumijima.net/api/forecast?city=400040
## 考察
- 一部APIが利用できない可能性あり
- axiosの既述の仕方が間違っている
- データを取得する名前の既述の仕方が違う

2022-06-10 23:53 UTC, taishi1116 requested changes
@kenta-0615

2022-06-10 23:53 UTC, taishi1116 commented on src/App.tsx
> +		axios.get(urlAPI).then((res) => {
# apiの仕様について
仕様書を読んだら/city/{number}でどの町かを指定しないといけないね

<img width="1136" alt="スクリーンショット 2022-06-11 8 49 26" src="https://user-images.githubusercontent.com/58138538/173163508-750596f7-006d-4ace-b88d-60efdab79238.png">



# 非同期処理について

今回APIを叩くので、非同期処理になる認識です！
APIからレスポンスが帰ってくるまでは、次の挙動を待ってもらわないといけないので
async/awaitを利用しないといけないと思います！

2022-06-12 06:16 UTC, kenta-0615 reviewed
close #10 
@taishi1116 
## 内容
- APIの取得を確認
- axiosの起動を確認
- APIの久留米市の天気を取得をtestで確認済み
## 確認手順
- npm startを実行
- webで検証を実行
- 久留米市の天気のデータをconsleで取得を確認

2022-06-12 11:59 UTC, taishi1116 commented
LGTMです！ただドラフトになってるので、PRをオープンしてマージしてください！

2022-06-12 17:16 UTC, merged