WIP: お天気アプリの実装
kenta-0615/react-weather-app pull request #31
Opened 2022-06-17 09:49 UTC by kenta-0615

close #30 
## 内容
- アプリの画面の実装
- 画面の大まかな表示は完了
  - HomePageの左右の今日の天気を表示する画面と１週間の天気を表示させる画面
- 地方の天気情報を調べるためのサイドバーを実装中
  - サーチボタンを押すとサイドバーが表示されそこに地域情報を表示
  - 地域のカードを押すとその地域の天気情報が表示される
## 現在の状況
- 左の画面、今日の天気を表示させる画面は実装完了
- 右の画面、１週間の天気と天気の情報（風の強さ等）を表示する画面は実装完了
- 地域の画面を表示させる画面の開閉式のサイドバーを実装中
  - useStateでButton.tsxに実装してSideBar.tsxに実装しようとしているがうまくいかず
  - 参考資料
  https://www.section.io/engineering-education/collapsible-sidebar-with-react-and-ant-design-library/
## 不明点
- hooksを使用してSideBarの実装方法
  - useStateを使用し、サイドバーの開閉の状態を設定
  - useStateが効かず

2022-06-17 21:29 UTC, kenta-0615 reviewed
@taishi1116 
## 内容
- WIP:お天気アプリの実装後のSidebarの実装
- useStateを使用してSideBarの開閉の実装は完了
## 現在の状況
- 開閉の実装はできたもののできていないところが多数
  - 開く際のbuttonはLeftScreen.tsxにあるSearch for placesに開く状態を持たせたい
  - 現在は、違うButtoncomponentに状態を持たせて開閉の実装をしている
  - 開閉時にもっとゆっくり開閉できるようにしたい
## 確認の仕方
- コードをcloneする
- npm startを実行

2022-06-17 23:02 UTC, taishi1116 commented
@kenta-0615 
エラーが発生しているんだけど、健太の手元だと動く?

<img width="3472" alt="スクリーンショット 2022-06-18 8 02 21" src="https://user-images.githubusercontent.com/58138538/174410855-45cbb3fe-dc0c-4560-94a3-ebb468380603.png">

2022-06-17 23:32 UTC, taishi1116 requested changes

2022-06-17 23:32 UTC, taishi1116 commented on src/components/main/SideBar.tsx
> +	const [shownSidebar, setShownSidebar] = useState(false);
変数名が気になりました！boolean型の変数はis,can,shouldなどのbe動詞疑問系にしてください

2022-06-17 23:32 UTC, taishi1116 commented on src/components/main/SideBar.tsx
> +					<button onClick={() => setShownSidebar(!shownSidebar)}>X</button>
# htmlについて

buttonタグを利用しているけど、ここってButtonコンポーネントを利用する形ではダメ?
せっかく作っているので可能な限り利用したいです！


# setstateがうまくいかない件について
多分原因はsetStateで直接`shownSidebar`を渡しちゃっていることだと思います！
下記文献が参考になるかと！
https://zenn.dev/syu/articles/3c4aa813b57b8c

2022-06-18 01:25 UTC, kenta-0615 reviewed
@taishi1116 
## 内容
- SideBarの変数名の変更
- Buttonタグで渡しているところをButtonコンポーネントを使用し実装
## 状況
- 現状指摘された部分を修正

2022-06-20 13:35 UTC, kenta-0615 reviewed
@taishi1116 
## 内容
- useStateの学習を踏まえたSideBarの実装
- Search for placesを押したらSideBarが開く
- SideBarの中にあるXのbuttonを押すとSideBarが閉じる
## 状況
- まずは、開閉の形が出来るよう実装
- まだ、修正の余地がある
## 備考
- アドバイスあればよろしくお願いします

2022-06-20 13:41 UTC, taishi1116 commented on src/components/main/SideBar.tsx
> +			{isClose && (
isCloseをしたらこのコンポーネントは何も表示しない形になるのが少し違和感あるかな！
分岐があるということはデフォルトで表示しているものがあるはずなんだけど、このコンポーネントだけ見ると何もないから。。

今回やりたいことってleftScreenの「本日の天気」と「サイドバー(検索フォーム)」を出しわけしたいんだよね？

LeftScreenにisCloseがあって、trueの時は本日の天気、falseの時はサイドバーを表示とかじゃダメなんだっけ?

2022-06-20 13:44 UTC, taishi1116 commented on src/components/main/SideBar.tsx
> +			{isClose && (
あとあれだ、iscloseがtrueの時に表示するであっている?

is close?っていう疑問がきているのに「yes」の時に表示しているから英語の意味とコードがずれている気がする

2022-06-21 12:39 UTC, taishi1116 commented
# 案1 引き続き上乗せのUIで実装する

- iscloseを変更する関数をpropsで渡してあげることで、sidebarの表示非表示を再現する

# 案2 上乗せのUIじゃなくてbooleanの値によって表示するUIを丸々かえる

2022-06-22 08:02 UTC, kenta-0615 reviewed
@taishi1116 @so0601pk 
## 内容
- SideBar.tsxとLeftScreenのuseStateを修正
- LeftScreen.tsxにuseStateをまとめた
- SideScreen.tsxにpropsでonCloseを渡す
## 状況
- デザインは実装中
- 一旦、open,closeの状態を実装

2022-06-22 09:08 UTC, taishi1116 commented on src/components/main/LeftScreen.tsx
> +	const toggle = () => setIsClose(!isClose);
関数は基本的に動作になると思うので、toggleという名詞だと何をするのかが分かりにくいです！
toggleの動作をまとめるのではなく、`openSideBar`、`closeSidebar`みたいな関数を作った方がわかりやすいかと

2022-06-22 10:37 UTC, kenta-0615 reviewed
@taishi1116 @so0601pk 
## 内容
- 指摘されたtoggle関数名の変更
- closeSideBarへ変更
## 状況
- 今回のPRもデザインは途中です

2022-06-23 04:48 UTC, kenta-0615 reviewed
@taishi1116 @so0601pk 
## 内容
- useStateの再度見直し
- Search for placesが押されたらSideBarが表示されることをtrueでonClickで設定
- onCloseにsetIsOpenを渡し、Search for placesが押されなければ表示させないおように設定
- プロップスでonCloseをサイドバーに渡し、XでClose出来るように設定
## 状況
- スタイルも修正
- Search for placesのOpenの動作異常なし
- SideBarのCloseの動作も異常なし
- APIの実装に移れると思います

2022-06-23 04:57 UTC, kenta-0615 reviewed
@taishi1116 @so0601pk 
## 内容
- AreaCardのiconに使用する画像追加
- Svg形式にて追加

2022-06-23 04:59 UTC, taishi1116 approved these changes
LGTM

2022-06-23 04:59 UTC, merged