README.mdの修正
kenta-0615/react-weather-app pull request #39
Opened 2022-07-14 21:23 UTC by kenta-0615

close #38 
## 内容
- README.mdの内容を変更
- 気をつけた点・学んだ点を追加
- デザインと仕様にAPIの仕様より表示内容が変更したことを追記

2022-07-15 01:19 UTC, taishi1116 requested changes

2022-07-15 01:19 UTC, taishi1116 commented on README.md
> +## 環境
環境構築から変えたり理由は何かある?

2022-07-15 01:19 UTC, taishi1116 commented on README.md
> +## 気をつけた点・学んだ点
現状だと、学んだのがコンポーネント指向とmapメソッドのみに見えるね。本当に学んだ点ってそれだけですか?


- storybook
- tailwindcss
- axiosを利用した非同期処理
- typescript開発による型

ここら辺書かないともったいないと思った
多分`気をつけた点・学んだ点`と`頑張ったこと`のセクションを一つにまとめたらいい気がしている

2022-07-15 01:19 UTC, taishi1116 commented on README.md
> +日本の特定地域の天気情報を取得する web アプリケーションです。
もっと詳細に書いてほしいと感じました！
何回かコメントしているけど、どんな人(開発初心者とかコード知らない面接官)が見てもわかる配慮された文章を意識して欲しいです！

今回のアプリだと下記あたりって開発している人しか知らない情報なので、追記が必要だと思います

- 画面読み込み時の最初の天気はどこの地域なのか
- 都道府県リストはなぜこの県だけ担っているのか
  - xmlから拝借する必要があり、全て記載するのは工数がかかるためとか必要じゃない?

2022-07-15 01:24 UTC, kenta-0615 commented on README.md
> +## 環境
特に理由は、ありません。

2022-07-15 01:25 UTC, kenta-0615 commented on README.md
> +## 気をつけた点・学んだ点
了解です！

2022-07-15 01:25 UTC, kenta-0615 commented on README.md
> +日本の特定地域の天気情報を取得する web アプリケーションです。
了解です！

2022-07-15 01:27 UTC, taishi1116 commented on README.md
> +## 環境
おけ！環境という文言に変えちゃうと、そのセクション内で環境構築手順まで書いてあるから少し違和感感じた！

理由なければ変更なしでも良いかと！

2022-07-16 07:34 UTC, kenta-0615 reviewed
@taishi1116 
# 内容
- 気をつけた点・学んだ点を頑張ったことに変更
- 概要を変更
- 使用技術にaxiosを追加

2022-07-17 05:24 UTC, taishi1116 commented on README.md
> +- 東京、横浜、広島、京都、福岡
`日本の特定地域の天気情報を取得する web アプリケーションです。`の後にいきなり都道府県が一覧として書かれているけど、これで他の人がわかるかな?

「調べれる地域」とか前置きタイトルがないと何の地域なのかがわからないと思います
自分が理解するための文章ではなく、**他の人が理解するための文章**がreadmeなのでその視点で書き直してください

2022-07-17 05:25 UTC, taishi1116 commented on README.md
> +  - 天気の情報を`axios`を使用し、気象庁のお天気の API を送受信ができるようにした。
送受信とあるけど、天気の更新みたいな機能な無かったはず

2022-07-17 05:26 UTC, taishi1116 commented on README.md
> +- `.map`メソッドを使用し、新しい配列の生成
mapメソッドはコンポーネントの再利用に該当しない気がする。

2022-07-17 05:30 UTC, taishi1116 commented on README.md
> +  - コンポーネントの名前を分かりやすく、TSX を利用することによって短い構文で可読性を高めた
ReactでJSXを扱うことはデフォルトでそうなので、アピールポイントにはつながらないかも。
それよりも「コンポーネントの名前をわかりやすく」と書いているので、「実装時に何を考えて名前をつけたのか」という頭の中で意識したことを落とし込んだ方がいいと思う

2022-07-17 23:16 UTC, kenta-0615 reviewed
@taishi1116 
# 内容
- 概要を修正
  - 特定に当たっている都道府県を記載
  - なぜ特定の都道府県しか取得しないのか理由を記載
- 頑張ったことの修正
  - axios、tailwind、コンポーネントの再利用、`.map`メソッドの内容の追記
# やったこと
- 読み返しをして自分で大丈夫なことを確認しました。
  - 自分には文章力に自身がないので添削お願いします。

2022-07-18 02:26 UTC, taishi1116 approved these changes

2022-07-18 12:17 UTC, merged